// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIxNTZ84ePzlniZ7eANwyj99pI5YejAY',
    appId: '1:870294890157:web:3ed1a61abc6e5e0d384824',
    messagingSenderId: '870294890157',
    projectId: 'healthyfood-58937',
    authDomain: 'healthyfood-58937.firebaseapp.com',
    storageBucket: 'healthyfood-58937.firebasestorage.app',
    measurementId: 'G-9JDEJ0KZR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWlJyjXfGCo1pdLORfsbYAgrwFZY4_E4',
    appId: '1:870294890157:android:017497bced4a3d95384824',
    messagingSenderId: '870294890157',
    projectId: 'healthyfood-58937',
    storageBucket: 'healthyfood-58937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvt8RDBA530N_tqJ00chkcmdo2oVBdrps',
    appId: '1:870294890157:ios:0d59a6612dbe008a384824',
    messagingSenderId: '870294890157',
    projectId: 'healthyfood-58937',
    storageBucket: 'healthyfood-58937.firebasestorage.app',
    iosBundleId: 'com.example.healthyFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvt8RDBA530N_tqJ00chkcmdo2oVBdrps',
    appId: '1:870294890157:ios:0d59a6612dbe008a384824',
    messagingSenderId: '870294890157',
    projectId: 'healthyfood-58937',
    storageBucket: 'healthyfood-58937.firebasestorage.app',
    iosBundleId: 'com.example.healthyFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIxNTZ84ePzlniZ7eANwyj99pI5YejAY',
    appId: '1:870294890157:web:901ede7f1daf6dc6384824',
    messagingSenderId: '870294890157',
    projectId: 'healthyfood-58937',
    authDomain: 'healthyfood-58937.firebaseapp.com',
    storageBucket: 'healthyfood-58937.firebasestorage.app',
    measurementId: 'G-ETW83E09N9',
  );
}
